export const uiText = {
    app: {
        name: '咕咕 War3 模型编辑器',
        loading: '加载中...',
    },
    menu: {
        file: '文件',
        edit: '编辑',
        mode: '模式',
        tools: '功能',
        help: '帮助',
        importModel: '导入模型',
        recentFiles: '最近文件',
        noRecentFiles: '暂无历史记录',
        clearRecentFiles: '清空历史记录',
        saveModel: '保存模型',
        copyModel: '复制模型',
        swapMdlMdx: '一键 MDL/MDX 互转',
        exportMdl: '另存为 MDL',
        exportMdx: '另存为 MDX',
        nodeManager: '节点管理器',
        cameraManager: '摄像机管理器',
        geosetManager: '多边形管理器',
        geosetAnimationManager: '多边形动画管理器',
        textureManager: '贴图管理器',
        textureAnimationManager: '贴图动画管理器',
        materialManager: '材质管理器',
        sequenceManager: '模型动作管理器',
        globalSequenceManager: '全局序列管理器',
        modelInfo: '模型信息',
        viewMode: '查看模式',
        geometryMode: '顶点模式',
        uvMode: 'UV 模式',
        animationMode: '动画模式',
        recalculateNormals: '重新计算法线',
        recalculateExtents: '重新计算模型顶点范围',
        transformModel: '修改模型位置/旋转/大小',
        modelOptimize: '模型优化',
        modelMerge: '模型合并',
        geosetVisibilityTool: '多边形动作显隐工具',
        addDeathAnimation: '添加死亡动画',
        removeLights: '删除所有光照',
        repairModel: '修复模型',
        mergeSameMaterials: '合并相同材质',
        cleanUnusedMaterials: '清理未使用的材质',
        cleanUnusedTextures: '清理未使用的贴图',
        modelText: '当前模型 TXT 文本',
        mpqBrowser: 'MPQ 浏览',
        batchMode: '批量模式',
        settings: '设置',
        debugConsole: '显示调试控制台',
        checkUpdate: '检查更新',
        about: '关于',
        statusOn: '已开启',
        statusOff: '已关闭',
        nodeRenderHidden: '已关闭',
        nodeRenderWireframe: '线框',
        nodeRenderSolid: '实体',
        quickToggle: {
            xyGrid: 'XY 网格',
            xzGrid: 'XZ 网格',
            yzGrid: 'YZ 网格',
            vertices: '顶点显示',
            nodes: '节点显示',
            skeleton: '渲染骨架',
            geosetTool: '可见性工具',
            collision: '碰撞节点',
            lights: '灯光对象',
            particles: '粒子显示',
            ribbons: '丝带显示',
            wireframe: '线框模式',
        },
    },
    layout: {
        nodeManager: '节点管理器',
        closeNodeManager: '关闭节点管理器',
        batchPreviewEmpty: '点击左侧模型卡片预览',
    },
    nodeDialog: {
        editNode: '编辑节点',
        titlePrefix: '编辑节点: ',
        nameGroup: '名称',
        nameRequired: '请输入节点名称',
        namePlaceholder: '节点名称',
        parentLabel: '父节点',
        parentPlaceholder: '父节点',
        noParent: '无父节点',
        pivotGroup: '轴心点（PIVT）',
        copyParentPivot: '复制父轴心',
        transformGroup: '变换',
        flagsGroup: '标记',
        dynamic: '动态',
        keyframes: '关键帧',
        translate: '位移',
        rotate: '旋转',
        scale: '缩放',
        dontInheritTranslation: '不继承位移',
        dontInheritRotation: '不继承旋转',
        dontInheritScaling: '不继承缩放',
        cameraAnchored: '相机锚定',
        billboarded: '广告牌',
        billboardedLockX: '广告牌锁定 X 轴',
        billboardedLockY: '广告牌锁定 Y 轴',
        billboardedLockZ: '广告牌锁定 Z 轴',
        save: '保存',
        cancel: '取消',
    },
    particleEmitter2Dialog: {
        title: 'II 型粒子发射器',
        savePreset: '保存粒子预设',
        presetNamePlaceholder: '输入预设名称',
        save: '保存',
        cancel: '取消',
        segment1: '第一部分',
        segment2: '第二部分',
        segment3: '第三部分',
        color: '颜色',
        alpha: '透明',
        scaling: '缩放',
        rendering: '渲染',
        textureId: '贴图 ID',
        replaceTextureHint: '可拖动替换贴图',
        overallScaling: '整体缩放',
        resetOverallScaling: '重置整体缩放',
        headerLifespan: '头部（持续时间）',
        headerDecay: '头部（衰减）',
        tailLifespan: '尾部（持续时间）',
        tailDecay: '尾部（衰减）',
        start: '开始',
        end: '结束',
        repeat: '重复',
        other: '其他',
        rows: '行数',
        lifeSpan: '持续时间',
        priorityPlane: '优先平面',
        time: '时间',
        columns: '列数',
        tailLength: '尾部长度',
        replaceableId: '可替换 ID',
        flags: '标记',
        unshaded: '无阴影',
        unfogged: '无雾化',
        lineEmitter: '线发射器',
        sortPrimsFarZ: '沿 Z 轴远向排列原始几何体',
        modelSpace: '模型空间',
        xyQuad: 'XY 象限',
        squirt: '喷射',
        head: '头部',
        tail: '尾部',
    },
    errorBoundary: {
        title: '界面区域发生错误',
        description: '已阻止异常扩散到整个应用。可以尝试重新加载当前区域，必要时关闭并重新打开对应面板。',
        retry: '重试',
        reloadPage: '刷新页面',
        details: '错误详情',
        defaultScope: '当前区域',
    },
} as const

export type UIText = typeof uiText
