export const uiText = {
    app: {
        name: '咕咕 War3 模型编辑器',
        version: 'v1.0.0',
        loading: '加载中...',
    },
    menu: {
        file: '文件',
        edit: '编辑',
        mode: '模式',
        tools: '工具',
        help: '帮助',
        importModel: '导入模型',
        recentFiles: '最近文件',
        noRecentFiles: '暂无历史记录',
        clearRecentFiles: '清空历史记录',
        saveModel: '保存模型',
        copyModel: '复制模型',
        swapMdlMdx: '一键 MDL/MDX 互转',
        exportMdl: '另存为 MDL',
        exportMdx: '另存为 MDX',
        nodeManager: '节点管理器',
        cameraManager: '镜头管理器',
        geosetManager: '多边形管理器',
        geosetAnimationManager: '多边形动画管理器',
        textureManager: '贴图管理器',
        textureAnimationManager: '贴图动画管理器',
        materialManager: '材质管理器',
        sequenceManager: '动作管理器',
        globalSequenceManager: '全局序列管理器',
        modelInfo: '模型信息',
        viewMode: '查看模式',
        geometryMode: '顶点模式',
        uvMode: 'UV 模式',
        animationMode: '动画模式',
        recalculateNormals: '重新计算法线',
        recalculateExtents: '重新计算模型范围',
        transformModel: '修改模型位置/旋转/缩放',
        modelOptimize: '模型优化',
        modelMerge: '模型合并',
        geosetVisibilityTool: '多边形显隐工具',
        addDeathAnimation: '添加死亡动画',
        removeLights: '删除所有灯光',
        repairModel: '修复模型',
        mergeSameMaterials: '合并相同材质',
        cleanUnusedMaterials: '清理未使用材质',
        cleanUnusedTextures: '清理未使用贴图',
        modelText: 'TXT 打开',
        mpqBrowser: 'MPQ 浏览',
        settings: '设置',
        debugConsole: '显示调试控制台',
        checkUpdate: '检查更新',
        about: '关于',
        statusOn: '已开启',
        statusOff: '已关闭',
        nodeRenderHidden: '已关闭',
        nodeRenderWireframe: '线框',
        nodeRenderSolid: '实体',
        quickToggle: {
            xyGrid: 'XY 网格',
            xzGrid: 'XZ 网格',
            yzGrid: 'YZ 网格',
            vertices: '顶点显示',
            nodes: '节点显示',
            skeleton: '骨架显示',
            geosetTool: '显隐工具',
            collision: '碰撞节点',
            lights: '灯光对象',
            particles: '粒子显示',
            ribbons: '丝带显示',
            wireframe: '线框模式',
        },
    },
    layout: {
        nodeManager: '节点管理器',
        closeNodeManager: '关闭节点管理器',
    },
    nodeDialog: {
        editNode: '编辑节点',
        titlePrefix: '编辑节点: ',
        nameGroup: '名称',
        nameRequired: '请输入节点名称',
        namePlaceholder: '节点名称',
        parentLabel: '父节点',
        parentPlaceholder: '选择父节点',
        noParent: '无父节点',
        pivotGroup: '轴心点',
        copyParentPivot: '复制父节点轴心',
        transformGroup: '变换',
        flagsGroup: '标记',
        dynamic: '动态化',
        keyframes: '关键帧',
        translate: '位移',
        rotate: '旋转',
        scale: '缩放',
        dontInheritTranslation: '不继承位移',
        dontInheritRotation: '不继承旋转',
        dontInheritScaling: '不继承缩放',
        cameraAnchored: '相机锚定',
        billboarded: '广告牌',
        billboardedLockX: '广告牌锁定 X 轴',
        billboardedLockY: '广告牌锁定 Y 轴',
        billboardedLockZ: '广告牌锁定 Z 轴',
        save: '保存',
        cancel: '取消',
    },
    particleEmitter2Dialog: {
        title: 'II 型粒子发射器',
        editPrefix: '编辑: ',
        savePreset: '保存粒子预设',
        presetDefaultName: '粒子预设',
        presetNamePlaceholder: '输入预设名称',
        saveSuccessTitle: '保存成功',
        saveSuccessDescriptionPrefix: '粒子预设已保存：',
        saveFailureTitle: '保存粒子预设失败',
        unknownError: '未知错误',
        save: '保存',
        cancel: '取消',
        confirm: '确定',
        visibility: '可见度',
        emissionRate: '发射速率',
        speed: '速度',
        variation: '变化',
        latitude: '纬度',
        width: '宽度',
        length: '长度',
        gravity: '重力',
        segment1: '第一部分',
        segment2: '第二部分',
        segment3: '第三部分',
        color: '颜色',
        alpha: '透明',
        scaling: '缩放',
        rendering: '渲染',
        textureId: '贴图 ID',
        replaceTextureHint: '可拖动替换贴图',
        overallScaling: '整体缩放',
        resetOverallScaling: '重置整体缩放',
        headerLifespan: '头部（持续时间）',
        headerDecay: '头部（衰减）',
        tailLifespan: '尾部（持续时间）',
        tailDecay: '尾部（衰减）',
        start: '开始',
        end: '结束',
        repeat: '重复',
        other: '其他',
        rows: '行数',
        lifeSpan: '持续时间',
        priorityPlane: '优先平面',
        time: '时间',
        columns: '列数',
        tailLength: '尾部长度',
        replaceableId: '可替换 ID',
        flags: '标记',
        unshaded: '无阴影',
        unfogged: '无雾化',
        lineEmitter: '线发射器',
        sortPrimsFarZ: '按 Z 轴远向排序原始多边形',
        modelSpace: '模型空间',
        xyQuad: 'XY 象限',
        squirt: '喷射',
        head: '头部',
        tail: '尾部',
        dynamic: '动态化',
    },
    particleEmitterDialog: {
        title: 'I 型粒子发射器',
        editHistory: '编辑粒子发射器',
        editPrefix: '编辑: ',
        emissionRate: '发射速率',
        lifeSpan: '持续时间',
        initVelocity: '初速度',
        gravity: '重力',
        longitude: '经度',
        latitude: '纬度',
        visibility: '可见度',
        other: '其他',
        pathLabel: '粒子文件路径',
        pathPlaceholder: '例如：Particles\\Dust.blp 或 .mdl/.tga',
        usesMdl: '发射器使用 MDL 文件',
        usesTga: '发射器使用 TGA 文件',
    },
    ribbonEmitterDialog: {
        title: '丝带发射器',
        dynamic: '动态化',
        color: '颜色',
        alpha: '透明度',
        visibility: '可见度',
        heightAbove: '上部高度',
        heightBelow: '下部高度',
        textureSlot: '贴图位置',
        height: '高度',
        position: '位置',
        other: '其他',
        materialId: '材质 ID:',
        materialLabelPrefix: '材质 ',
        rowsHint: '行数（单张贴图内图像行数）',
        columnsHint: '列数（单张贴图内图像列数）',
        emissionRate: '发射速率:',
        lifeSpan: '持续时间:',
        gravity: '重力:',
        confirm: '确定',
        cancel: '取消',
    },
    lightDialog: {
        title: '灯光',
        editHistory: '编辑灯光',
        editPrefix: '编辑: ',
        dynamic: '动态化',
        color: '颜色',
        ambientColor: '环境色',
        attenuationStart: '衰减开始',
        attenuationEnd: '衰减结束',
        intensity: '光照强度',
        ambientIntensity: '环境强度',
        visibility: '可见度',
        other: '其他',
        type: '类型:',
        omnidirectional: '全方向光 (Omnidirectional)',
        directional: '方向光 (Directional)',
        ambient: '环境光 (Ambient)',
        confirm: '确定',
        cancel: '取消',
    },
    eventObjectDialog: {
        title: '事件对象',
        track: '事件轨迹',
        framePrefix: '帧',
        noFrames: '暂无事件帧',
        framePlaceholder: '帧号',
        add: '添加',
        remove: '删除',
        eventData: '事件数据',
        type: '类型:',
        data: '数据:',
        todoPlaceholder: '后续完善',
        identifierPlaceholder: '标识符（目前仅作显示占位）',
        other: '其他',
        globalSequenceId: '全局序列 ID:',
        confirm: '确定',
        cancel: '取消',
    },
    collisionShapeDialog: {
        title: '碰撞形状',
        type: '类型',
        box: '立方体',
        sphere: '球体',
        vertex1: '顶点 1',
        vertex2: '顶点 2',
        sphereCenterHint: '（球体为球心）',
        other: '其他',
        sphereRadius: '球体半径:',
        confirm: '确定',
        cancel: '取消',
    },
    transformModelDialog: {
        title: '修改模型位置/旋转/缩放',
        translation: '平移 (Translation)',
        rotation: '旋转 (Rotation)',
        scale: '缩放 (Scale)',
        syncScale: '同步缩放比例',
    },
    renameNodeDialog: {
        title: '重命名节点',
        nameLabel: '节点名称',
        nameRequired: '请输入节点名称',
        placeholder: '输入新名称',
        confirm: '确定',
        cancel: '取消',
    },
    createNodeDialog: {
        title: '创建新节点',
        nameLabel: '节点名称',
        nameRequired: '请输入节点名称',
        namePlaceholder: '例如: NewBone',
        typeLabel: '节点类型',
        typeRequired: '请选择节点类型',
        parentLabel: '父节点',
        parentPlaceholder: '选择父节点（留空为根节点）',
        defaultName: 'default',
        typeOptions: {
            bone: 'Bone (骨骼)',
            helper: 'Helper (辅助体)',
            attachment: 'Attachment (附着体)',
            light: 'Light (灯光)',
            particleEmitter1: 'ParticleEmitter1 (I 型粒子发射器)',
            particleEmitter2: 'ParticleEmitter2 (II 型粒子发射器)',
            ribbonEmitter: 'RibbonEmitter (丝带发射器)',
            eventObject: 'EventObject (事件对象)',
            collisionShape: 'CollisionShape (碰撞形状)',
        },
    },
    dynamicField: {
        dynamic: '动态化',
    },
    about: {
        title: '关于',
        activationStatus: '授权状态',
        permanent: '永久',
        qqVerification: 'QQ 群验证',
        timeLimited: '时限',
        reviewDate: '复验日期',
        expirationDate: '到期日期',
        upgradeHint: '输入高级版激活码可升级',
        inactive: '未激活',
        loading: '加载中...',
        replaceActivationCode: '升级/替换激活码',
        enterActivationCode: '输入激活码',
        activationPlaceholder: '请输入激活码',
        activating: '验证中...',
        activate: '激活',
        confirm: '确定',
    },
    errorBoundary: {
        title: '界面区域发生错误',
        description: '已阻止异常扩散到整个应用。可以尝试重新加载当前区域，必要时关闭并重新打开对应面板。',
        retry: '重试',
        reloadPage: '刷新页面',
        details: '错误详情',
        defaultScope: '当前区域',
    },
} as const

export type UIText = typeof uiText
