export const DEFERRED_PREVIEW_FIELD_NAMES = new Set([
    'Visibility',
    'EmissionRate',
    'Speed',
    'Variation',
    'Latitude',
    'Width',
    'Length',
    'Gravity',
    'Seg1Alpha',
    'Seg1Scaling',
    'Seg2Alpha',
    'Seg2Scaling',
    'Seg3Alpha',
    'Seg3Scaling',
    'HeadLifeSpanStart',
    'HeadLifeSpanEnd',
    'HeadLifeSpanRepeat',
    'HeadDecayStart',
    'HeadDecayEnd',
    'HeadDecayRepeat',
    'TailLifeSpanStart',
    'TailLifeSpanEnd',
    'TailLifeSpanRepeat',
    'TailDecayStart',
    'TailDecayEnd',
    'TailDecayRepeat',
    'Rows',
    'LifeSpan',
    'PriorityPlane',
    'Time',
    'Columns',
    'TailLength',
    'ReplaceableId',
]);

export const PROP_TO_ANIM_KEY: Record<string, string> = {
    EmissionRate: 'EmissionRateAnim',
    Speed: 'SpeedAnim',
    Variation: 'VariationAnim',
    Latitude: 'LatitudeAnim',
    Width: 'WidthAnim',
    Length: 'LengthAnim',
    Gravity: 'GravityAnim',
    Visibility: 'VisibilityAnim',
};
